title                        : "Jishen Lin"

description                  : "Bachelor’s Degree in Software Engineering, Specialization in Machine Intelligence, School of Computer Science and Technology, Tongji University."

repository                   : "MinmusLin/MinmusLin.github.io"

google_analytics_id          : # get google_analytics_id from https://analytics.google.com/analytics/

google_site_verification     : # get google_site_verification from https://search.google.com/search-console/about

bing_site_verification       : # get bing_site_verification from https://www.bing.com/webmasters/about

baidu_site_verification      : # get baidu_site_verification from https://ziyuan.baidu.com/login/index?u=/site/index

google_scholar_stats_use_cdn : true

author:
  name             : "Jishen Lin (林继申)"
  avatar           : "images/android-chrome-512x512.png"
  bio              : "Tongji University"
  location         : "Shanghai, China"
  employer         :
  pubmed           :
  googlescholar    : # "https://scholar.google.com/citations?user=GOOGLE_SCHOLAR_ID"
  email            : "minmuslin@outlook.com"
  researchgate     :
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "MinmusLin"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      :
  lastfm           :
  linkedin         :
  dblp             :
  orcid            :
  pinterest        :
  soundcloud       :
  stackoverflow    :
  steam            :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :

include:
  - .htaccess
  - _pages
  - files

exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor

keep_files:
  - .git
  - .svn

encoding: "utf-8"

markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown: kramdown

highlighter: rouge

lsi: false

excerpt_separator: "\n\n"

incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/

timezone: Asia/Shanghai

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

compress_html:
  clippings: all
  ignore:
    envs: development